### ISSUE TITLE
The app crashes after I clicked on share 

### ISSUE THREAD

**Issue by masudr4n4** [ologe/canaree-music-player#1]
<h4>Actual behavior</h4>
when I click share the app crashes.
<h4>Expected behavior</h4>
I expected that I can click the share button and share my files successfully.
<h4>How to reproduce</h4>
<ol>
<li>Download the latest version app from playstore.</li>
<li>Open the app</li>
<li>Allow all the permission and start the app</li>
<li>Click Folder</li>
<li>Click a folder which containing music</li>
<li>Choose any music ,at the side of the music there is three vertical dots, click on that.</li>
<li>Click share from the list</li>
<li>See error</li>
</ol>
Information
<ul>
<li>App version:v2.1.1</li>
<li>OS:Android 6.0.1,5.1</li>
<li>Device:Samsung J5,symphony v85</li>
</ul>
<h4>Recording of the bug</h4>
<a href="https://youtu.be/hrFdeZ6Q0fo">https://youtu.be/hrFdeZ6Q0fo</a>
<h4>Logcat</h4>
<pre>
<code>
04-19 21:50:43.510 25570 25570 E AndroidRuntime: FATAL EXCEPTION: main

04-19 21:50:43.510 25570 25570 E AndroidRuntime: Process: dev.olog.msc, PID: 25570

04-19 21:50:43.510 25570 25570 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.support.v4.content.FileProvider.a(Unknown Source)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.support.v4.content.FileProvider.a(Unknown Source)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at dev.olog.msc.presentation.aUx.nul.a(Unknown Source)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at dev.olog.msc.presentation.aUx.aUx.com7.onMenuItemClick(Unknown Source)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:252)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:801)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:944)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:430)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:346)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1576)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3962)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.widget.AbsListView$7.run(AbsListView.java:6042)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

04-19 21:50:43.510 25570 25570 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
</code>
</pre>
@ologe

**Comment by ologe** [comment]
I'm noticing that for some reason it's using the FileProvider from the support v4 package instead of AndroidX.

Since on my device the crash isn't happening, try to add in the AndroidManifest the following provider
and then please let me know if crash is fixed.

```
   <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
  </provider>
```

**Comment by masudr4n4** [comment]
Is your device rooted?try to reproduce the bug in real non-rooted device.Its happening with my two device mention in the past.I don't know how to add the provider,i used real device not emulator.
