### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by eomobile** [ologe/canaree-music-player#15]
ERROR: Could not get unknown property 'last_fm_key' for BuildType_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=true, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.

**Comment by ologe** [comment]
Please follow the build instructions in the [README.md](https://github.com/ologe/canaree-music-player).

You have to create a `gradle.properties` file in the project root folder and paste the content from the README.

- Get your last fm credentials you have to register your app [here](https://github.com/ologe/canaree-music-player).
- The aes password can be any string
- Get an ad mob key you have to register your app [here](https://admob.google.com/home/)
- Keep all the quotation marks

**Comment by mrsr2win** [comment]
ERROR: Could not read script 'J:\android proj\canaree-music-player-master\Users\eugeniuolog\AndroidStudioProjects\ExoPlayer\core_settings_min.gradle' as it does not exist.

**Comment by ologe** [comment]
Please follow the build instructions in the README.md.

**Comment by mrsr2win** [comment]
i follow Method 1 not working

**Comment by mrsr2win** [comment]
i got only one error 

ERROR: Could not read script 'J:\android proj\canaree-music-player-master\Users\eugeniuolog\AndroidStudioProjects\ExoPlayer\core_settings_min.gradle' as it does not exist.
Open File

**Comment by ologe** [comment]
Sorry my fault, I forgot to add a step in **Method 1**. I'll update the README right now!

**Comment by mrsr2win** [comment]
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/38472641/67023420-69ee8e80-f120-11e9-9b6f-5054fbbbf549.png">

**Comment by ologe** [comment]
Just updated the readme. However, you have to open `settings.gradle` and comment the last three lines.

**Comment by mrsr2win** [comment]
why comment that

**Comment by ologe** [comment]
Because with method 1 you will use the [remote version of ExoPlayer](https://github.com/google/ExoPlayer)
