### ISSUE TITLE
Could you please add an open-source license?

### ISSUE THREAD

**Issue by Michaeldgeek** [ologe/canaree-music-player#16]
The project has no license so it cannot be used as-is.  See (https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)

**Comment by fahadtaric** [comment]
Can we add/change features in this project and publish it?

**Comment by ologe** [comment]
I didn't attach any license exactly for that reason. The project is for personal use only, you cannot redistribute it.
