### ISSUE TITLE
Exoplayer 2.11 Issues

### ISSUE THREAD

**Issue by nvlashi** [ologe/canaree-music-player#23]
I've followed the directions for compiling this but when I run it I get the following errors:

service-music/src/main/java |  
-- | --
dev/olog/service/music/interfaces/ExoPlayerListenerWrapper.kt |  
'onPlaybackParametersChanged' overrides nothing |  
'onTracksChanged' overrides nothing |  
'onTimelineChanged' overrides nothing |  
dev/olog/service/music/player/crossfade/CrossFadePlayer.kt |  
Val cannot be reassigned |  
Val cannot be reassigned |

**Comment by ologe** [comment]
Hi @nvlashi, that's because of the latest version of ExoPlayer (2.11), I'm working on it. To fix this problem please use ExoPlayer v2.10.x
