### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by asmw** [ologe/canaree-music-player#26]
Hi,

I could not find out what license this source is released under. Since https://github.com/xdrop/fuzzywuzzy is listed as a dependency and under GPLv2 I assume this is GPLv2 as well?

**Comment by ologe** [comment]
This repo hasn't a license because I don't want it to be redistributable, but for personal use only. 
But feel free to contribute, fork or consult it 😄

**Comment by asmw** [comment]
Ok, that's fine but you might want to look into that GPL dependency then, as your usage might not be OK in that case.
